# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module Friar::Ast::Atom::ArrayLiteral::Expression; end
module Friar::Ast::Atom::Unary::Primary; end
module Friar::Value::Bool; end
module Friar::Value::Int; end
module Friar::Value::Null; end
module Friar::Value::Str; end
